### ISSUE TITLE
一些ios平台运行的错误疑问

### ISSUE THREAD

**Issue by David-Slake** [Kaby-Lake/SAMScript#2]
大佬好 我按照wiki介绍安装完插件后 一直没办法获取到油猴上的扩展 显示"fail to get init data"
可以帮忙看看么 孩子真的想不想被封了

非常感谢

这是一些环境介绍
12 pro ios 16.1
外网环境（连UNNCVPN仍无改善）

**Comment by Kaby-Lake** [comment]
我有空把README补全一下，This issue will track such process
