### ISSUE TITLE
一些小建议

### ISSUE THREAD

**Issue by Iron-fence** [Kaby-Lake/SAMScript#4]
作者好，您的脚本修改的应该是请假页面第一条请假信息和对应的请假详情的内容。刚才我试了一下，如果第一条请假信息是“被撤销”或者“拒绝”的状态，那么修改后显示的请假状态是不变的。或许可以在readme加一个提示，修改前sams的第一条请假信息必须是“通过”的状态才行，感谢！

**Comment by Kaby-Lake** [comment]
收到，感谢您的建议。我今明天发一个版，支持修改请假内容能力，并且自动把第一条请假申请的状态也改成通过
